In [3]:
import numpy as np 

import pandas as pd 

def datafromsheet(): 

    inputdata = pd.read_csv('C:/Users/jaggu/Desktop/BALANCE SCALE AND WEIGHT.csv', header = None) 
    print("dataset from excel :",inputdata)
      

def start(): 

    data = datafromsheet() 

       
start()  

dataset from excel :      0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]


In [9]:
import numpy as np 

import pandas as pd 

def datafromsheet(): 

    inputdata = pd.read_csv('C:/Users/jaggu/Desktop/BALANCE SCALE AND WEIGHT.csv', header = None) 
    
    print("dataset from excel :",inputdata)
    print ("Dataset Length: ", len(inputdata)) 
    print ("Dataset Shape: ", inputdata.shape)  

    return inputdata 



def start(): 

    data = datafromsheet() 

       
start()


    

dataset from excel :      0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]
Dataset Length:  625
Dataset Shape:  (625, 5)


In [10]:
import numpy as np 

import pandas as pd 

def datafromsheet(): 

    inputdata = pd.read_csv('C:/Users/jaggu/Desktop/BALANCE SCALE AND WEIGHT.csv', header = None) 
    
    print("dataset from excel :",inputdata)
    print ("Dataset Length: ", len(inputdata)) 
    print ("Dataset Shape: ", inputdata.shape)  

    return inputdata 



def start(): 

    data = datafromsheet() 

       
start()
X, Y, X_train, X_test, y_train, y_test = splitdataset(data) 

dataset from excel :      0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]
Dataset Length:  625
Dataset Shape:  (625, 5)


NameError: name 'splitdataset' is not defined

In [17]:
import numpy as np 

import pandas as pd 

def datafromsheet(): 

    inputdata = pd.read_csv('C:/Users/jaggu/Desktop/BALANCE SCALE AND WEIGHT.csv', header = None) 
    
    print("dataset from excel :",inputdata)
    print ("Dataset Length: ", len(inputdata)) 
    print ("Dataset Shape: ", inputdata.shape)  

    return inputdata 

def splitdataset(inputdata): 

  
    X = inputdata.values[:, 1:5] 

    Y = inputdata.values[:, 0] 

    X_train, X_test, y_train, y_test = train_test_split(  

    X, Y, test_size = 0.3, random_state = 100) 

    print( X,Y)  

    return X, Y, X_train, X_test, y_train, y_test 


def start(): 

    data = datafromsheet() 
    return data
       
d=start()
X, Y, X_train, X_test, y_train, y_test = splitdataset(d) 

dataset from excel :      0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]
Dataset Length:  625
Dataset Shape:  (625, 5)


NameError: name 'train_test_split' is not defined

In [18]:
import numpy as np 

import pandas as pd 

def datafromsheet(): 

    inputdata = pd.read_csv('C:/Users/jaggu/Desktop/BALANCE SCALE AND WEIGHT.csv', header = None) 
    
    print("dataset from excel :",inputdata)
    print ("Dataset Length: ", len(inputdata)) 
    print ("Dataset Shape: ", inputdata.shape)  

    return inputdata 

def splitdataset(inputdata): 

  
    X = inputdata.values[:, 1:5] 

    Y = inputdata.values[:, 0] 

    X_train, X_test, y_train, y_test = train_test_split(  

    X, Y, test_size = 0.3, random_state = 100) 

    print( X,Y)  

    return X, Y, X_train, X_test, y_train, y_test 


def start(): 

    data = datafromsheet() 
    return data
       
d=start()
X, Y, X_train, X_test, y_train, y_test = splitdataset(d) 

dataset from excel :      0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]
Dataset Length:  625
Dataset Shape:  (625, 5)


NameError: name 'train_test_split' is not defined

In [21]:
import numpy as np 

import pandas as pd
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

def datafromsheet(): 

    inputdata = pd.read_csv('C:/Users/jaggu/Desktop/BALANCE SCALE AND WEIGHT.csv', header = None) 
    
    print("dataset from excel :",inputdata)
    print ("Dataset Length: ", len(inputdata)) 
    print ("Dataset Shape: ", inputdata.shape)  

    return inputdata 

def splitdataset(inputdata): 

  
    X = inputdata.values[:, 1:5] 

    Y = inputdata.values[:, 0] 

    X_train, X_test, y_train, y_test = train_test_split(  

    X, Y, test_size = 0.3, random_state = 100) 

    print( X,Y)  

    return X, Y, X_train, X_test, y_train, y_test 


def start(): 

    data = datafromsheet() 
    return data
       
d=start()
X, Y, X_train, X_test, y_train, y_test = splitdataset(d) 

dataset from excel :      0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]
Dataset Length:  625
Dataset Shape:  (625, 5)
[[1 1 1 1]
 [1 1 1 2]
 [1 1 1 3]
 ...
 [5 5 5 3]
 [5 5 5 4]
 [5 5 5 5]] ['B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'B' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'B' 'R'
 'R' 'L' 'R' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'L' 'L' 'L' 'B' 'R' 'L' 'B' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R'
 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'L' 'L' 'B' 'L' 'L' 'R'
 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'L'
 'B' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 

In [23]:
import numpy as np 

import pandas as pd
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

def datafromsheet(): 

    inputdata = pd.read_csv('C:/Users/jaggu/Desktop/BALANCE SCALE AND WEIGHT.csv', header = None) 
    
    print("dataset from excel :",inputdata)
    print ("Dataset Length: ", len(inputdata)) 
    print ("Dataset Shape: ", inputdata.shape)  

    return inputdata 

def splitdataset(inputdata): 

  
    X = inputdata.values[:, 1:5] 

    Y = inputdata.values[:, 0] 

    X_train, X_test, y_train, y_test = train_test_split(  

    X, Y, test_size = 0.3, random_state = 100) 

    print( X,Y)  

    return X, Y, X_train, X_test, y_train, y_test 

def usingentropy(X_train, X_test, y_train): 

    entropy = DecisionTreeClassifier( 

            criterion = "entropy", random_state = 100, 

            max_depth = 3, min_samples_leaf = 5) 

    entropy.fit(X_train, y_train) 

    return entropy 


def start(): 

    data = datafromsheet() 
    return data
       
d=start()
X, Y, X_train, X_test, y_train, y_test = splitdataset(d) 
entropy = usingentropy(X_train, X_test, y_train)

dataset from excel :      0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]
Dataset Length:  625
Dataset Shape:  (625, 5)
[[1 1 1 1]
 [1 1 1 2]
 [1 1 1 3]
 ...
 [5 5 5 3]
 [5 5 5 4]
 [5 5 5 5]] ['B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'B' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'B' 'R'
 'R' 'L' 'R' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'L' 'L' 'L' 'B' 'R' 'L' 'B' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R'
 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'L' 'L' 'B' 'L' 'L' 'R'
 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'L'
 'B' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 

In [25]:
 import numpy as np 

import pandas as pd
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

def datafromsheet(): 

    inputdata = pd.read_csv('C:/Users/jaggu/Desktop/BALANCE SCALE AND WEIGHT.csv', header = None) 
    
    print("dataset from excel :",inputdata)
    print ("Dataset Length: ", len(inputdata)) 
    print ("Dataset Shape: ", inputdata.shape)  

    return inputdata 

def splitdataset(inputdata): 

  
    X = inputdata.values[:, 1:5] 

    Y = inputdata.values[:, 0] 

    X_train, X_test, y_train, y_test = train_test_split(  

    X, Y, test_size = 0.3, random_state = 100) 

    print( X,Y)  

    return X, Y, X_train, X_test, y_train, y_test 

def usingentropy(X_train, X_test, y_train): 

    entropy = DecisionTreeClassifier( 

            criterion = "entropy", random_state = 100, 

            max_depth = 3, min_samples_leaf = 5) 

    entropy.fit(X_train, y_train) 

    return entropy 

def prediction(X_test, clf_object): 

    y_pred = clf_object.predict(X_test) 

    print("Predicted values:") 

    print(y_pred) 

    return y_pred 

def cal_accuracy(y_test, y_pred): 

    
    print ("Accuracy : ", 

    accuracy_score(y_test,y_pred)*100)

def start(): 

    data = datafromsheet() 
    return data
       
d=start()
X, Y, X_train, X_test, y_train, y_test = splitdataset(d) 
entropy = usingentropy(X_train, X_test, y_train)

print("Results Using Entropy:")

y_pred_entropy = prediction(X_test,entropy) 

dataset from excel :      0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]
Dataset Length:  625
Dataset Shape:  (625, 5)
[[1 1 1 1]
 [1 1 1 2]
 [1 1 1 3]
 ...
 [5 5 5 3]
 [5 5 5 4]
 [5 5 5 5]] ['B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'B' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'B' 'R'
 'R' 'L' 'R' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'L' 'L' 'L' 'B' 'R' 'L' 'B' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R'
 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'L' 'L' 'B' 'L' 'L' 'R'
 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'L'
 'B' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 

In [26]:
import numpy as np 

import pandas as pd
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

def datafromsheet(): 

    inputdata = pd.read_csv('C:/Users/jaggu/Desktop/BALANCE SCALE AND WEIGHT.csv', header = None) 
    
    print("dataset from excel :",inputdata)
    print ("Dataset Length: ", len(inputdata)) 
    print ("Dataset Shape: ", inputdata.shape)  

    return inputdata 

def splitdataset(inputdata): 

  
    X = inputdata.values[:, 1:5] 

    Y = inputdata.values[:, 0] 

    X_train, X_test, y_train, y_test = train_test_split(  

    X, Y, test_size = 0.3, random_state = 100) 

    print( X,Y)  

    return X, Y, X_train, X_test, y_train, y_test 

def usingentropy(X_train, X_test, y_train): 

    entropy = DecisionTreeClassifier( 

            criterion = "entropy", random_state = 100, 

            max_depth = 3, min_samples_leaf = 5) 

    entropy.fit(X_train, y_train) 

    return entropy 

def prediction(X_test, clf_object): 

    y_pred = clf_object.predict(X_test) 

    print("Predicted values:") 

    print(y_pred) 

    return y_pred 

def accuracy(y_test, y_pred): 

    
    print ("Accuracy : ", 

    accuracy_score(y_test,y_pred)*100)

def start(): 

    data = datafromsheet() 
    return data
       
d=start()
X, Y, X_train, X_test, y_train, y_test = splitdataset(d) 
entropy = usingentropy(X_train, X_test, y_train)

print("Results Using Entropy:")

y_pred_entropy = prediction(X_test,entropy) 

accuracy(y_test, y_pred_entropy) 

dataset from excel :      0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]
Dataset Length:  625
Dataset Shape:  (625, 5)
[[1 1 1 1]
 [1 1 1 2]
 [1 1 1 3]
 ...
 [5 5 5 3]
 [5 5 5 4]
 [5 5 5 5]] ['B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'B' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'B' 'R'
 'R' 'L' 'R' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'L' 'L' 'L' 'B' 'R' 'L' 'B' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R'
 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'L' 'L' 'B' 'L' 'L' 'R'
 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'L'
 'B' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 