In [3]:
import numpy as np 

import pandas as pd 

def datafromsheet(): 

    inputdata = pd.read_csv('C:/Users/jaggu/Desktop/BALANCE SCALE AND WEIGHT.csv', header = None) 
    print("dataset from excel :",inputdata)
      

def start(): 

    data = datafromsheet() 

       
start()  

dataset from excel :      0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]


In [9]:
import numpy as np 

import pandas as pd 

def datafromsheet(): 

    inputdata = pd.read_csv('C:/Users/jaggu/Desktop/BALANCE SCALE AND WEIGHT.csv', header = None) 
    
    print("dataset from excel :",inputdata)
    print ("Dataset Length: ", len(inputdata)) 
    print ("Dataset Shape: ", inputdata.shape)  

    return inputdata 



def start(): 

    data = datafromsheet() 

       
start()


    

dataset from excel :      0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]
Dataset Length:  625
Dataset Shape:  (625, 5)


In [10]:
import numpy as np 

import pandas as pd 

def datafromsheet(): 

    inputdata = pd.read_csv('C:/Users/jaggu/Desktop/BALANCE SCALE AND WEIGHT.csv', header = None) 
    
    print("dataset from excel :",inputdata)
    print ("Dataset Length: ", len(inputdata)) 
    print ("Dataset Shape: ", inputdata.shape)  

    return inputdata 



def start(): 

    data = datafromsheet() 

       
start()
X, Y, X_train, X_test, y_train, y_test = splitdataset(data) 

dataset from excel :      0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]
Dataset Length:  625
Dataset Shape:  (625, 5)


NameError: name 'splitdataset' is not defined

In [6]:
import numpy as np 

import pandas as pd 

def datafromsheet(): 

    inputdata = pd.read_csv('C:/Users/jaggu/Desktop/BALANCE SCALE AND WEIGHT.csv', header = None) 
    
    print("dataset from excel :",inputdata)
    print ("Dataset Length: ", len(inputdata)) 
    print ("Dataset Shape: ", inputdata.shape)  

    return inputdata 

def splitdataset(inputdata): 

  
    X = inputdata.values[:, 1:5] 

    Y = inputdata.values[:, 0] 

    Xtrain, Xtest, ytrain, ytest = traintestsplit(  

    X, Y, test_size = 0.3, random_state = 100) 

    print( X,Y)  

    return X, Y, Xtrain, Xtest, ytrain, ytest 


def start(): 

    data = datafromsheet() 
    return data
       
d=start()
X, Y, Xtrain, Xtest, ytrain, ytest = splitdataset(d) 

dataset from excel :      0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]
Dataset Length:  625
Dataset Shape:  (625, 5)


NameError: name 'traintestsplit' is not defined

In [7]:
import numpy as np 

import pandas as pd 

def datafromsheet(): 

    inputdata = pd.read_csv('C:/Users/jaggu/Desktop/BALANCE SCALE AND WEIGHT.csv', header = None) 
    
    print("dataset from excel :",inputdata)
    print ("Dataset Length: ", len(inputdata)) 
    print ("Dataset Shape: ", inputdata.shape)  

    return inputdata 

def splitdataset(inputdata): 

  
    X = inputdata.values[:, 1:5] 

    Y = inputdata.values[:, 0] 

    Xtrain, Xtest, ytrain, ytest = traintestsplit(  

    X, Y, testsize = 0.3, randomstate = 100) 

    print( X,Y)  

    return X, Y, Xtrain, Xtest, ytrain, ytest 


def start(): 

    data = datafromsheet() 
    return data
       
d=start()
X, Y, Xtrain, Xtest, ytrain, ytest = splitdataset(d) 

dataset from excel :      0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]
Dataset Length:  625
Dataset Shape:  (625, 5)


NameError: name 'traintestsplit' is not defined

In [15]:
import numpy as np 

import pandas as pd


def datafromsheet(): 

    inputdata = pd.read_csv('C:/Users/jaggu/Desktop/BALANCE SCALE AND WEIGHT.csv', header = None) 
    
    print("dataset from excel :",inputdata)
    print ("Dataset Length: ", len(inputdata)) 
    print ("Dataset Shape: ", inputdata.shape)  

    return inputdata 


from sklearn.model_selection import train_test_split 



def splitdataset(inputdata): 

  
    X = inputdata.values[:, 1:5] 

    Y = inputdata.values[:, 0] 

    Xtrain, Xtest, ytrain, ytest = train_test_split(  

    X, Y, test_size = 0.3, random_state = 100) 

    print( X,Y)  

    return X, Y, Xtrain, Xtest, ytrain, ytest 


def start(): 

    data = datafromsheet() 
    return data
       
d=start()
X, Y, Xtrain, Xtest, ytrain, ytest = splitdataset(d) 

dataset from excel :      0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]
Dataset Length:  625
Dataset Shape:  (625, 5)
[[1 1 1 1]
 [1 1 1 2]
 [1 1 1 3]
 ...
 [5 5 5 3]
 [5 5 5 4]
 [5 5 5 5]] ['B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'B' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'B' 'R'
 'R' 'L' 'R' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'L' 'L' 'L' 'B' 'R' 'L' 'B' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R'
 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'L' 'L' 'B' 'L' 'L' 'R'
 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'L'
 'B' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 

In [18]:
import numpy as np 

import pandas as pd
 


def datafromsheet(): 

    inputdata = pd.read_csv('C:/Users/jaggu/Desktop/BALANCE SCALE AND WEIGHT.csv', header = None) 
    
    print("dataset from excel :",inputdata)
    print ("Dataset Length: ", len(inputdata)) 
    print ("Dataset Shape: ", inputdata.shape)  

    return inputdata 

from sklearn.model_selection import train_test_split 




def splitdataset(inputdata): 

  
    X = inputdata.values[:, 1:5] 

    Y = inputdata.values[:, 0] 

    Xtrain, Xtest, ytrain, ytest = train_test_split(  

    X, Y, test_size = 0.3, random_state = 100) 

    print( X,Y)  

    return X, Y, Xtrain, Xtest, ytrain, ytest 


def usingentropy(Xtrain, Xtest, ytrain): 

    entropy = DecisionTreeClassifier( 

            criterion = "entropy", random_state = 100, 

            max_depth = 3, min_samples_leaf = 5) 

    entropy.fit(Xtrain, ytrain) 

    return entropy 


def start(): 

    data = datafromsheet() 
    return data
       
d=start()
X, Y, Xtrain, Xtest, ytrain, ytest = splitdataset(d) 
entropy = usingentropy(Xtrain, Xtest, ytrain)

dataset from excel :      0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]
Dataset Length:  625
Dataset Shape:  (625, 5)
[[1 1 1 1]
 [1 1 1 2]
 [1 1 1 3]
 ...
 [5 5 5 3]
 [5 5 5 4]
 [5 5 5 5]] ['B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'B' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'B' 'R'
 'R' 'L' 'R' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'L' 'L' 'L' 'B' 'R' 'L' 'B' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R'
 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'L' 'L' 'B' 'L' 'L' 'R'
 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'L'
 'B' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 

In [20]:
 import numpy as np 

import pandas as pd

 


def datafromsheet(): 

    inputdata = pd.read_csv('C:/Users/jaggu/Desktop/BALANCE SCALE AND WEIGHT.csv', header = None) 
    
    print("dataset from excel :",inputdata)
    print ("Dataset Length: ", len(inputdata)) 
    print ("Dataset Shape: ", inputdata.shape)  

    return inputdata 

from sklearn.model_selection import train_test_split 




def splitdataset(inputdata): 

  
    X = inputdata.values[:, 1:5] 

    Y = inputdata.values[:, 0] 

    Xtrain, Xtest, ytrain, ytest = train_test_split(  

    X, Y, test_size = 0.3, random_state = 100) 

    print( X,Y)  

    return X, Y, Xtrain, Xtest, ytrain, ytest 


def usingentropy(Xtrain, Xtest, ytrain): 

    entropy = DecisionTreeClassifier( 

            criterion = "entropy", random_state = 100, 

            max_depth = 3, min_samples_leaf = 5) 

    entropy.fit(Xtrain, ytrain) 

    return entropy 

def prediction(Xtest, clfobject): 

    ypred = clfobject.predict(Xtest) 

    print("Predicted values:") 

    print(ypred) 

    return ypred 


def start(): 

    data = datafromsheet() 
    return data
       
       
d=start()
X, Y, Xtrain, Xtest, ytrain, ytest = splitdataset(d) 
entropy = usingentropy(Xtrain, Xtest, ytrain)

print("Results Using Entropy:")

ypredentropy = prediction(Xtest,entropy) 

dataset from excel :      0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]
Dataset Length:  625
Dataset Shape:  (625, 5)
[[1 1 1 1]
 [1 1 1 2]
 [1 1 1 3]
 ...
 [5 5 5 3]
 [5 5 5 4]
 [5 5 5 5]] ['B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'B' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'B' 'R'
 'R' 'L' 'R' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'L' 'L' 'L' 'B' 'R' 'L' 'B' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R'
 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'L' 'L' 'B' 'L' 'L' 'R'
 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'L'
 'B' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 

In [23]:
import numpy as np 

import pandas as pd

 


def datafromsheet(): 

    inputdata = pd.read_csv('C:/Users/jaggu/Desktop/BALANCE SCALE AND WEIGHT.csv', header = None) 
    
    print("dataset from excel :",inputdata)
    print ("Dataset Length: ", len(inputdata)) 
    print ("Dataset Shape: ", inputdata.shape)  

    return inputdata 

from sklearn.model_selection import train_test_split 




def splitdataset(inputdata): 

  
    X = inputdata.values[:, 1:5] 

    Y = inputdata.values[:, 0] 

    Xtrain, Xtest, ytrain, ytest = train_test_split(  

    X, Y, test_size = 0.3, random_state = 100) 

    print( X,Y)  

    return X, Y, Xtrain, Xtest, ytrain, ytest 


def usingentropy(Xtrain, Xtest, ytrain): 

    entropy = DecisionTreeClassifier( 

            criterion = "entropy", random_state = 100, 

            max_depth = 3, min_samples_leaf = 5) 

    entropy.fit(Xtrain, ytrain) 

    return entropy 

def prediction(Xtest, clfobject): 

    ypred = clfobject.predict(Xtest) 

    print("Predicted values:") 

    print(ypred) 

    return ypred 


def start(): 

    data = datafromsheet() 
    return data
       
       
d=start()
X, Y, Xtrain, Xtest, ytrain, ytest = splitdataset(d) 
entropy = usingentropy(Xtrain, Xtest, ytrain)

print("Results Using Entropy:")

ypredentropy = prediction(Xtest,entropy) 

from sklearn.metrics import accuracy_score
print ("Accuracy : ",  accuracy_score(ytest,ypredentropy)*100)



dataset from excel :      0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]
Dataset Length:  625
Dataset Shape:  (625, 5)
[[1 1 1 1]
 [1 1 1 2]
 [1 1 1 3]
 ...
 [5 5 5 3]
 [5 5 5 4]
 [5 5 5 5]] ['B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'B' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'B' 'R'
 'R' 'L' 'R' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'L' 'L' 'L' 'B' 'R' 'L' 'B' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R'
 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'L' 'L' 'B' 'L' 'L' 'R'
 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'L'
 'B' 'R' 'R' 'R' 'B' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 